### ISSUE TITLE
Slash in Regexp causes syntax highlighting to highlight remaining tokens as string

### ISSUE THREAD

**Issue by sudarshang** [ananthakumaran/typescript.el#43] opened 2017-07-07 22:26 UTC
```typescript
const forwardSlashSourcePath = sourcePath.replace(/\\/g, '/');
```

To replicate this paste the above in an Emacs buffer with Typescript enabled. All the tokens after the `/\\/` have the font face string.

**Comment by lddubeau** [comment] 2017-07-07 22:29
Duplicate of #34.

**Closed by lddubeau** 2017-07-07 22:29 UTC
